- name: Build image and with buildargs
  local_action:
    command: docker build -t ginix /home/deployer/godeploy/nginx
- name: Deploy 1st Container for Nginix
  local_action:
    command: docker run -itd --name gonginx -p 80:80 ginix /bin/bash
