- name: Build image and with buildargs
  shell: cd /home/deployer/godeploy/nginx && docker build -t ginix .
- name: Deploy 1st Container for Nginix
  shell: docker run -itd --name gonginx -p 80:80 ginix /bin/bash
